import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service — Lana AI',
  description: 'Terms of Service for Lana AI and hey-lana.ai.',
}

const sections = [
  {
    title: '1. Acceptance of Terms',
    body: [
      'By accessing or using hey-lana.ai or any service provided by Lana AI ("Lana AI", "we", "us", "our"), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, please do not use the service.',
    ],
  },
  {
    title: '2. Use of the Service',
    body: [
      'Lana AI provides an AI-powered digital assistant and related content workflow tools designed to help businesses communicate with their customers and manage their content. You agree to use the service only for lawful purposes and in accordance with these Terms.',
    ],
  },
  {
    title: '3. Accounts and Access',
    body: [
      'Certain features of the service may require you to provide account information or connect third-party accounts. You are responsible for maintaining the confidentiality of any credentials and for all activity that occurs under your account.',
    ],
  },
  {
    title: '4. User Content and Permissions',
    body: [
      'Any content you submit, upload, or connect through the service — including text, images, video, or account data — remains your property. By using the service, you grant Lana AI a limited license to access and process that content solely to provide the requested service to you.',
    ],
  },
  {
    title: '5. TikTok and Third-Party Integrations',
    body: [
      'Where TikTok or other third-party integrations are connected, the service only acts after the account owner authorizes access. Any upload or publishing workflow is intended for content created, owned, or approved by the account owner.',
      'Use of any connected third-party platform is also subject to that platform’s own terms of service and policies.',
    ],
  },
  {
    title: '6. Approved Content Workflow',
    body: [
      'Any automated or assisted content workflow (including drafting, scheduling, or publishing) will only proceed with content that has been created by, owned by, or explicitly approved by the account owner prior to any action being taken.',
    ],
  },
  {
    title: '7. Prohibited Use',
    body: [
      'You agree not to use the service to upload or distribute unlawful, infringing, or harmful content, to misrepresent your identity or authorization, to interfere with the operation of the service, or to attempt unauthorized access to any part of the platform or connected accounts.',
    ],
  },
  {
    title: '8. Intellectual Property',
    body: [
      'All content, branding, and technology associated with Lana AI and hey-lana.ai — excluding user-submitted content — are the property of Lana AI and its parent company, Oner Media Production, and may not be copied, modified, or distributed without permission.',
    ],
  },
  {
    title: '9. Disclaimers',
    body: [
      'The service is provided "as is" without warranties of any kind, whether express or implied. Lana AI does not guarantee that the service will be uninterrupted, error-free, or that outputs generated by the assistant will always be accurate or suitable for every purpose.',
    ],
  },
  {
    title: '10. Limitation of Liability',
    body: [
      'To the fullest extent permitted by law, Lana AI shall not be liable for any indirect, incidental, or consequential damages arising from your use of, or inability to use, the service.',
    ],
  },
  {
    title: '11. Changes to These Terms',
    body: [
      'We may update these Terms of Service from time to time. Continued use of the service after changes are posted constitutes acceptance of the revised terms. The date below reflects the most recent update.',
    ],
  },
  {
    title: '12. Contact',
    body: ['If you have questions about these Terms, contact us at ask@hey-lana.ai.'],
  },
]

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#08080f] text-white">
      <div className="pointer-events-none fixed inset-0 overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[400px] bg-violet-500/[0.05] rounded-full blur-[100px]" />
      </div>

      <div className="relative border-b border-white/[0.06] px-4 sm:px-6 py-4 flex items-center gap-4 backdrop-blur-xl bg-[#08080f]/80">
        <Link
          href="/"
          className="flex items-center gap-2 text-white/45 hover:text-white transition-colors text-sm"
        >
          <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="m12 19-7-7 7-7" />
            <path d="M19 12H5" />
          </svg>
          Back
        </Link>
        <div className="h-4 w-px bg-white/10" />
        <Link href="/" className="text-lg font-bold">
          Lana<span className="text-violet-400">.</span>AI
        </Link>
      </div>

      <div className="relative max-w-3xl mx-auto px-4 sm:px-6 py-16">
        <h1 className="text-3xl sm:text-4xl font-bold tracking-tight mb-2">Terms of Service</h1>
        <p className="text-white/35 text-sm mb-12">Last updated: July 1, 2026</p>

        <div className="glass-card p-8 sm:p-10 space-y-9">
          {sections.map((section) => (
            <div key={section.title}>
              <h2 className="text-lg font-semibold text-white mb-3">{section.title}</h2>
              <div className="space-y-3">
                {section.body.map((p, i) => (
                  <p key={i} className="text-white/55 text-sm leading-relaxed">
                    {p}
                  </p>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
